name: TypeScript Action
author: Austen Stone
description: A TypeScript Action
branding:
  icon: "plus"
  color: "blue"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  include-gitignore:
    description: Whether to include files in .gitignore
    default: 'true'
    required: false
  ignore-default:
    description: Whether to ignore the default `*` files
    default: 'false'
    required: false
  fail-if-not-covered:
    description: Whether to fail if not all files are covered
    default: 'false'
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
