name: CODEOWNERS Coverage
on:
  workflow_dispatch:

jobs:
  run:
    name: Check CODEOWNERS Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          ignore-default: 'true'