name: CODEOWNERS Coverage Changed
on:
  push:
  pull_request:

jobs:
  run:
    name: Run Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: changed-files
        uses: tj-actions/changed-files@v29.0.3
      - run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - uses: ./
        with:
          ignore-default: 'true'